### ISSUE TITLE
Error in line 172 of rmmq.hpp

### ISSUE THREAD

**Issue by donatigiacomo91** [RobertBakaric/rmmq#1]
my compiler give me an error on line 172 of rmmq.hpp

why you use a vector as a function?

**Comment by RobertBakaric** [comment]
Hi,

nice to hear someone is taking  interest in my scriblings. I trully do not know why you are getting an error on that line it is not suppose produce any errors there. At that point I am simple initializing a range vector using a class constructor. Alternatively I could've copied the vector manually but if there is an option to do that automatically I saw no reason not to use it.

What compiler are you using ??  I'm running rmmq under gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3 
What is the error message you're getting ??

**Comment by donatigiacomo91** [comment]
i download only the file "rmmq.hpp" and i add it to my project in Clion, the compiler apparently work correctly, and also the library apparently work well: it return the correct values if i use it in this form:

RMMQ<int> rmmq(scores);

but the ide say me: "called object is not a function", also if i call rmmq.destroy() i get an out of bound exception from vector swap.

the compile directly raise the "error: type 'vector<int>' does not provide a call operator range(vec);" if i use the lib in this form:

RMMQ<int> rm;
rm.make(scores);

**Comment by RobertBakaric** [comment]
U R absolutely right. I corrected my mistakes. It should work now.  Sorry for the inconvenience!! And thank you for reporting this

Cheers

**Comment by donatigiacomo91** [comment]
There is also the line 153 of the file rmmq.hpp. I don't know this syntax. you can give me some info about it? it as a name? in this line you use range as i function.

RMMQ<TInt>::RMMQ(const vector<TInt>& vec) : range(vec), ST<TInt> (vec){}

**Comment by RobertBakaric** [comment]
Well as you probably notice I like generic programing style, which maybe is sometimes hard to read but I find it much flexible regarding data types and function overloads. 

As far as you inquiry regarding line 153 goes, well this is one way you can initialize a class member. For example you could do something like this 

`template<typename T>`
`class X {`
`T variable;`
`public:`
`X(T var);`
`};`

`X<T>::T(T var){`
`variable = T;`
`}`
 or you could do it like this 

`
X<T>::T(T var) : variable(var){}
`
Now, for class members of basic types, it makes no difference, thsi is simply a matter of taste I guess, but  for calss members like objects, if they are not set, they are default-constructed. if that happens then i wasted a construction on nothing because I need to do it once again with my object. so by stating initially the object with which my class object should be constructed I am saving construction  time. Clearly in this example it makes little difference but it is a good practice that pays off latter when objects get huge.  So you could say it is a habit :)

**Comment by donatigiacomo91** [comment]
Good. Nice lib, nice developer.
